# Generated by Django 3.2.8 on 2021-10-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telegram', models.TextField()),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('phone_number', models.TextField()),
                ('paid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('telegram', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField()),
                ('chat_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField()),
                ('chat_id', models.PositiveIntegerField()),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargobot_mailing.customermessage')),
            ],
        ),
    ]
